specification:
    path:     /specification
    defaults: { _controller: api.document_controller:get }


swagger-json:
    resource: "default.json"
    type: swagger-mock

swagger-yaml:
    resource: "api.yml"
    type: swagger-mock
