services:
    swagger.controller.default:
        class: Zwartpet\SwaggerMockerBundle\Controller\DefaultController
        arguments: ['%kernel.root_dir%', '@logger' ]

    api.document_controller:
        class: Zwartpet\SwaggerMockerBundle\Controller\OpenApiDocumentController
        arguments: ['@swagger.document.repository']

    cache.documents:
        class: Doctrine\Common\Cache\ArrayCache
        calls:
          - [ setNamespace, ['documents'] ]

    swagger.mocker.route_loader:
        class: Zwartpet\SwaggerMockerBundle\Routing\SwaggerMockRouteLoader
        arguments: ['@swagger.document.repository']
        tags:
           - { name: routing.loader }

    swagger.stub_loader:
        class: Zwartpet\SwaggerMockerBundle\Services\StubLoader
        arguments: ['%kernel.root_dir%']
